PfplBundle\Entity\Activites:
    type: entity
    table: ACTIVITES
    id:
        acId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: AC_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        acDescr:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: AC_DESCR
    lifecycleCallbacks: {  }
