PfplBundle\Entity\Clients:
    type: entity
    table: CLIENTS
    id:
        clId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CL_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        reId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: RE_ID
        clRef:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CL_REF
        clRaisonsoc:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CL_RAISONSOC
        clSiret:
            type: string
            nullable: true
            length: 14
            options:
                fixed: false
            column: CL_SIRET
        clAdresse1:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CL_ADRESSE1
        clAdresse2:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CL_ADRESSE2
        clCp:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: CL_CP
        clVille:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CL_VILLE
        clPays:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CL_PAYS
        clTel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CL_TEL
        clFax:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CL_FAX
        clMail:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CL_MAIL
        clWeb:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CL_WEB
        clDtAdhesion:
            type: datetime
            nullable: true
            column: CL_DT_ADHESION
        clLogo:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: CL_LOGO
        clPrescript:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CL_PRESCRIPT
        clTarif:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CL_TARIF
        clCodePromo:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CL_CODE_PROMO
        clStatus:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CL_STATUS
        clAdhesion:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CL_ADHESION
        clActivite:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CL_ACTIVITE
        clGroupe:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CL_GROUPE
        clClassif:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CL_CLASSIF
        clEffectif:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CL_EFFECTIF
        clCa:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CL_CA
        clMasqHa:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CL_MASQ_HA
        clMasqVt:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CL_MASQ_VT
        clEtiquette:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: CL_ETIQUETTE
        clTempo:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CL_TEMPO
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    lifecycleCallbacks: {  }
