PfplBundle\Entity\ClientsAdresses:
    type: entity
    table: CLIENTS_ADRESSES
    id:
        caId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CA_ID
            generator:
                strategy: IDENTITY
    fields:
        clId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CL_ID
        caType:
            type: string
            nullable: true
            length: 1
            options:
                fixed: false
            column: CA_TYPE
        caRaisonsoc:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CA_RAISONSOC
        caAdresse1:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CA_ADRESSE1
        caAdresse2:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CA_ADRESSE2
        caCp:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: CA_CP
        caVille:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CA_VILLE
        caPays:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CA_PAYS
        caPrincipale:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CA_PRINCIPALE
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    lifecycleCallbacks: {  }
