PfplBundle\Entity\CommandeEntete:
    type: entity
    table: COMMANDE_ENTETE
    indexes:
        IDX_BD3767A9FD61DBA2:
            columns:
                - ME_ID
    id:
        ceId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CE_ID
            generator:
                strategy: IDENTITY
    fields:
        clId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CL_ID
        ceDate:
            type: date
            nullable: true
            column: CE_DATE
        cePort:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CE_PORT
        cePortTva:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CE_PORT_TVA
        ceTotal:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CE_TOTAL
        ceEtiqCb:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CE_ETIQ_CB
        ceEtiqPv:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CE_ETIQ_PV
        ceTempo:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CE_TEMPO
        ceStatus:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CE_STATUS
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    manyToOne:
        me:
            targetEntity: MessageEntete
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ME_ID:
                    referencedColumnName: ME_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
