PfplBundle\Entity\Presse:
    type: entity
    table: PRESSE
    id:
        ppId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PP_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        ppTitre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: PP_TITRE
        ppLogo:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: PP_LOGO
        ppImage:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: PP_IMAGE
        ppDate:
            type: datetime
            nullable: true
            column: PP_DATE
        ppPage:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: PP_PAGE
        ppDescr:
            type: text
            nullable: true
            length: 16
            options:
                fixed: false
            column: PP_DESCR
        ppOrdre:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PP_ORDRE
        ppTempo:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: PP_TEMPO
        ppStatus:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PP_STATUS
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    lifecycleCallbacks: {  }
