PfplBundle\Entity\Regions:
    type: entity
    table: REGIONS
    id:
        reId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: RE_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        reNom:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: RE_NOM
        rePole:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: RE_POLE
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    lifecycleCallbacks: {  }
