GccpBundle\Entity\ClientsNotes:
    type: entity
    table: CLIENTS_NOTES
    id:
        cnId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CN_ID
            generator:
                strategy: IDENTITY
    fields:
        clId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CL_ID
        cnNote:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: CN_NOTE
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    lifecycleCallbacks: {  }
