GccpBundle\Entity\Contrats:
    type: entity
    table: CONTRATS
    indexes:
        IDX_B45BA520DA314FF6:
            columns:
                - CO_CATEGORIE
        IDX_B45BA5203F592A49:
            columns:
                - CL_ID
    id:
        coId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CO_ID
            generator:
                strategy: IDENTITY
    fields:
        coUser:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CO_USER
        coTier:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CO_TIER
        coDescr:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: CO_DESCR
        coDebut:
            type: datetime
            nullable: true
            column: CO_DEBUT
        coRenouv:
            type: datetime
            nullable: true
            column: CO_RENOUV
        coDuree:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CO_DUREE
        coPreavis:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CO_PREAVIS
        coContact:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CO_CONTACT
        coContTel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CO_CONT_TEL
        coContMail:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: CO_CONT_MAIL
        coConfident:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CO_CONFIDENT
        coMontant:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CO_MONTANT
        coEcheance:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CO_ECHEANCE
        coModePaie:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CO_MODE_PAIE
        coComment:
            type: text
            nullable: true
            length: 16
            options:
                fixed: false
            column: CO_COMMENT
        coStatus:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CO_STATUS
        coAlert:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CO_ALERT
        coTempo:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CO_TEMPO
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    manyToOne:
        coCategorie:
            targetEntity: ContratsCat
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CO_CATEGORIE:
                    referencedColumnName: CC_ID
            orphanRemoval: false
        cl:
            targetEntity: Clients
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CL_ID:
                    referencedColumnName: CL_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
