GccpBundle\Entity\ContratsCat:
    type: entity
    table: CONTRATS_CAT
    indexes:
        IDX_AF50DB674D0C1225:
            columns:
                - SO_ID
    id:
        ccId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CC_ID
            generator:
                strategy: IDENTITY
    fields:
        ccDescr:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CC_DESCR
        ccDate:
            type: datetime
            nullable: true
            column: CC_DATE
    manyToOne:
        so:
            targetEntity: Societes
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                SO_ID:
                    referencedColumnName: SO_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
