GccpBundle\Entity\Options:
    type: entity
    table: OPTIONS
    id:
        opId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: OP_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        opDescr:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: OP_DESCR
        opFormat:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: OP_FORMAT
    lifecycleCallbacks: {  }
