GccpBundle\Entity\ParamFixes:
    type: entity
    table: PARAM_FIXES
    id:
        pfId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PF_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        pfSmtp:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: PF_SMTP
        pfSmtpUser:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: PF_SMTP_USER
        pfSmtpPass:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: PF_SMTP_PASS
        pfPays:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_PAYS
        pfPaysDescr:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: PF_PAYS_DESCR
        pfSiteUrl:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
            column: PF_SITE_URL
        pfAccueil:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_ACCUEIL
        pfAdherer:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_ADHERER
        pfContact:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_CONTACT
        pfDecouvrir:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_DECOUVRIR
        pfRecherche:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_RECHERCHE
        pfConnecter:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_CONNECTER
        pfEspacePrive:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_ESPACE_PRIVE
        pfEspacePriveF:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_ESPACE_PRIVE_F
        pfInfosUtiles:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_INFOS_UTILES
        pfTickets:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_TICKETS
        pfPlusPart:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: PF_PLUS_PART
        pfPlusConseil:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: PF_PLUS_CONSEIL
        pfPrixAffiche:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_PRIX_AFFICHE
        pfRegion:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PF_REGION
        pfMessAccueil:
            type: string
            nullable: true
            length: 2000
            options:
                fixed: false
            column: PF_MESS_ACCUEIL
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    lifecycleCallbacks: {  }
