imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@SiteBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:
        enable_annotations: true
        enabled: true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:     centrale_achat_jb
        connections:
            centrale_achat_jb:
                driver_class:   Realestate\MssqlBundle\Driver\PDODblib\Driver
                host:           "%database_host%"
                user:           "%database_user%"
                password:       "%database_password%"
                dbname:         "CENTRALE_ACHAT_JB"
            centrale_produits:
                driver_class:   Realestate\MssqlBundle\Driver\PDODblib\Driver
                host:           "185.29.149.32"
                user:           "AC_JBAGOSTIN"
                password:       "35H7Hjvy"
                dbname:         "CENTRALE_PRODUITS_JB"


    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:  centrale_achat_jb
        entity_managers:
            centrale_achat_jb:
                connection: centrale_achat_jb
                mappings:
                    AchatCentraleCrmBundle : ~
            centrale_produits:
                connection: centrale_produits
                mappings:
                    SiteBundle : ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%port%"
    auth_mode:  "%auth_mode%"
    spool:     { type: memory }


assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    bundles:        [ SiteBundle ]
    filters:
        cssrewrite: ~


fos_rest:
    body_listener: true
    format_listener:
        rules:
            - { path: '^/Agence', priorities: [ json, '*/*'], fallback_format: html , prefer_extension: false }
            - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig


web_profiler:
    # display the web debug toolbar at the bottom of pages with
    # a summary of profiler info
    toolbar:              false
    position:             top

    # gives you the opportunity to look at the collected data
    # before following the redirect
    intercept_redirects: false

    # Exclude AJAX requests in the web debug toolbar for specified paths
    excluded_ajax_paths:  ^/bundles|^/_wdt


