imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@SiteBundle/Resources/config/services.yml" }
    - { resource: "@FunecapBundle/Resources/config/services.yml" }
    - { resource: "@AchatCentraleBundle/Resources/config/services.yml" }
    - { resource: "@RocEclercBundle/Resources/config/services.yml" }
    - { resource: "@GccpBundle/Resources/config/services.yml" }
    - { resource: "@PfplBundle/Resources/config/services.yml" }
    - { resource: "@ProductBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:
        enable_annotations: true
        enabled: true
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    translator: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        client_service: "@site.service.client_services"


services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }



# Doctrine Configuration
doctrine:
    dbal:
        default_connection:     centrale_achat_jb
        connections:
            centrale_achat_jb:
                driver_class:   Realestate\MssqlBundle\Driver\PDODblib\Driver
                host:           "%database_host%"
                user:           "%database_user%"
                password:       "%database_password%"
                dbname:         "CENTRALE_ACHAT_JB"
                charset:  UTF-8
                options:
                    ansi_nulls: on
                    ansi_warnings: on
                    20: false
            centrale_produits:
                driver_class:   Realestate\MssqlBundle\Driver\PDODblib\Driver
                host:           "185.29.149.144"
                user:           "AC_JBAGOSTIN"
                password:       "35H7Hjvy"
                dbname:         "CENTRALE_PRODUITS_JB"
                charset:  UTF-8
                options:
                    ansi_nulls: on
                    ansi_warnings: on
                    20: false
            centrale_funecap:
                 driver_class:   Realestate\MssqlBundle\Driver\PDODblib\Driver
                 host:           "185.29.149.144"
                 user:           "AC_JBAGOSTIN"
                 password:       "35H7Hjvy"
                 dbname:         "CENTRALE_FUNECAP"
                 charset:  UTF-8
                 options:
                     ansi_nulls: on
                     ansi_warnings: on
                     20: false
            achat_centrale:
                driver_class: Realestate\MssqlBundle\Driver\PDODblib\Driver
                host:         "185.29.149.144"
                user:         "AC_JBAGOSTIN"
                password:     "35H7Hjvy"
                dbname:       "CENTRALE_ACHAT"
                charset:  UTF-8
                options:
                    ansi_nulls: on
                    ansi_warnings: on
                    20: false
            roc_eclerc:
                driver_class: Realestate\MssqlBundle\Driver\PDODblib\Driver
                host:         "185.29.149.144"
                user:         "AC_JBAGOSTIN"
                password:     "35H7Hjvy"
                dbname:       "CENTRALE_ROC_ECLERC"
                charset:  UTF-8
                options:
                     ansi_nulls: on
                     ansi_warnings: on
                     20: false
            centrale_gccp:
                driver_class: Realestate\MssqlBundle\Driver\PDODblib\Driver
                host:         "185.29.149.144"
                user:         "AC_JBAGOSTIN"
                password:     "35H7Hjvy"
                dbname:       "CENTRALE_GCCP"
                charset:  UTF-8
                options:
                    ansi_nulls: on
                    ansi_warnings: on
                    20: false
            centrale_pascal_leclerc:
                driver_class: Realestate\MssqlBundle\Driver\PDODblib\Driver
                host:         "185.29.149.144"
                user:         "AC_JBAGOSTIN"
                password:     "35H7Hjvy"
                dbname:       "CENTRALE_PFPL"
                charset:  UTF-8
                options:
                    ansi_nulls: on
                    ansi_warnings: on
                    20: false
            ac_produits:
                driver_class: Realestate\MssqlBundle\Driver\PDODblib\Driver
                host:         "185.29.149.144"
                user:         "AC_JBAGOSTIN"
                password:     "35H7Hjvy"
                dbname:       "CENTRALE_PRODUITS"
                charset:  UTF-8
                options:
                    ansi_nulls: on
                    ansi_warnings: on
                    20: false


    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager:  centrale_achat_jb
        entity_managers:
            centrale_achat_jb:
                connection: centrale_achat_jb
                mappings:
                    AchatCentraleCrmBundle : ~
            centrale_produits:
                connection: centrale_produits
                mappings:
                    SiteBundle : ~
            centrale_funecap:
                connection: centrale_funecap
                mappings:
                    FunecapBundle : ~
            achat_centrale:
                connection: achat_centrale
                mappings:
                    AchatCentraleBundle: ~
            roc_eclerc:
                connection: roc_eclerc
                mappings:
                    RocEclercBundle: ~
            centrale_gccp:
                connection: centrale_gccp
                mappings:
                    GccpBundle: ~
            centrale_pascal_leclerc:
                connection: centrale_pascal_leclerc
                mappings:
                    PfplBundle: ~
            ac_produits:
                connection: ac_produits
                mappings:
                    ProductBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%port%"
    auth_mode:  "%auth_mode%"
    logging:   '%kernel.debug%'

fos_rest:
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    format_listener:
        rules:
            - { path: '^/Agence', priorities: [ json, '*/*'], fallback_format: html , prefer_extension: true }
            - { path: '^/Action', priorities: [ json, '*/*'], fallback_format: html , prefer_extension: true }
            - { path: ^/,  stop: true }
    param_fetcher_listener: true
    view:
        mime_types:
            json: ['application/json']
        view_response_listener: 'force'
        formats:
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
    exception:
            enabled: true
            messages:
                Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true

ivory_google_map:
    map:
        debug: "%kernel.debug%"
        language: "%locale%"
        api_key: AIzaSyDqTv8u6IGLtrKvwNIM6bwsBM_DLLHHHb8
    geocoder:
        client: httplug.client.default
        message_factory: httplug.message_factory.default
        format: json

httplug:
    classes:
        client: Http\Adapter\Guzzle6\Client
        message_factory: Http\Message\MessageFactory\GuzzleMessageFactory
    clients:
        acme:
            factory: httplug.factory.guzzle6