
site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

Api:
    resource: "@AchatCentraleCrmBundle/Controller/"
    type:     annotation
    prefix:   /

clients:
    type:   rest
    resource: "@AchatCentraleCrmBundle/Controller/ClientsController.php"

action:
    type:   rest
    resource: "@AchatCentraleCrmBundle/Controller/ActionController.php"

achat_centrale:
    resource: "@AchatCentraleBundle/Controller/"
    type:     annotation
    prefix:   /

pfpl:
    resource: "@PfplBundle/Controller/"
    type:     annotation
    prefix:   /

gccp:
    resource: "@GccpBundle/Controller/"
    type:     annotation
    prefix:   /

roc_eclerc:
    resource: "@RocEclercBundle/Controller/"
    type:     annotation
    prefix:   /
