site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

achat_centrale_crm:
    resource: "@AchatCentraleCrmBundle/Resources/config/crm_routing/routing.yml"
    prefix:   /crm


Api:
    resource: "@AchatCentraleCrmBundle/Controller/"
    type:     annotation
    prefix:   /


clients:
    type:   rest
    resource: "@AchatCentraleCrmBundle/Controller/ClientsController.php"