site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

achat_centrale_crm:
    resource: "@AchatCentraleCrmBundle/Resources/config/routing.yml"
    prefix:   /crm


users:
    type:   rest
    resource: "@AchatCentraleCrmBundle/Controller/UserController.php"


clients:
    type:   rest
    resource: "@AchatCentraleCrmBundle/Controller/ClientController.php"
