FunecapBundle\Entity\ClientsUsers:
    type: entity
    table: CLIENTS_USERS
    indexes:
        IDX_E2E056FD3F592A49:
            columns:
                - CL_ID
    id:
        ccId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CC_ID
            generator:
                strategy: IDENTITY
    fields:
        puId:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: PU_ID
        ccPrenom:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CC_PRENOM
        ccNom:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CC_NOM
        ccFonction:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CC_FONCTION
        ccTel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CC_TEL
        ccGsm:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CC_GSM
        ccFax:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CC_FAX
        ccMail:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CC_MAIL
        ccPass:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
                default: '123456'
            column: CC_PASS
        ccNiveau:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CC_NIVEAU
        circuitValidation:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: CIRCUIT_VALIDATION
        ccStatus:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CC_STATUS
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    manyToOne:
        cl:
            targetEntity: Clients
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CL_ID:
                    referencedColumnName: CL_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
