FunecapBundle\Entity\CommandeEntete:
    type: entity
    table: COMMANDE_ENTETE
    id:
        ceId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CE_ID
            generator:
                strategy: IDENTITY
    fields:
        meId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ME_ID
        clId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CL_ID
        ceDate:
            type: date
            nullable: true
            column: CE_DATE
        cePort:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CE_PORT
        cePortTva:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CE_PORT_TVA
        ceTotal:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CE_TOTAL
        ceEtiqCb:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: CE_ETIQ_CB
        ceEtiqPv:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: CE_ETIQ_PV
        ceTempo:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: CE_TEMPO
        ceStatus:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: CE_STATUS
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    lifecycleCallbacks: {  }
