FunecapBundle\Entity\Faq:
    type: entity
    table: FAQ
    id:
        qfId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: QF_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        qfQuestion:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: QF_QUESTION
        qfReponse:
            type: text
            nullable: true
            length: 16
            options:
                fixed: false
            column: QF_REPONSE
        qfOrdre:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: QF_ORDRE
        qfDate:
            type: datetime
            nullable: true
            column: QF_DATE
    lifecycleCallbacks: {  }
