FunecapBundle\Entity\NousContacter:
    type: entity
    table: NOUS_CONTACTER
    id:
        ncId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: NC_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        ncSociete:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: NC_SOCIETE
        ncNom:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: NC_NOM
        ncPrenom:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: NC_PRENOM
        ncSiret:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: NC_SIRET
        ncMail:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: NC_MAIL
        ncTel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: NC_TEL
        ncObjet:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: NC_OBJET
        ncCommentaire:
            type: string
            nullable: true
            length: 7000
            options:
                fixed: false
            column: NC_COMMENTAIRE
        ncTempo:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: NC_TEMPO
        ncDate:
            type: datetime
            nullable: true
            column: NC_DATE
    lifecycleCallbacks: {  }
