<?php

namespace AchatCentrale\CrmBundle\Repository;

/**
 * ClientsGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientsGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
