ProductBundle\Entity\FournPlus:
    type: entity
    table: FOURN_PLUS
    id: {  }
    fields:
        fpPdfTitre1:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: FP_PDF_TITRE1
        fpPdf1:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: FP_PDF1
        fpPdfTitre2:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: FP_PDF_TITRE2
        fpPdf2:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: FP_PDF2
        fpPlus:
            type: string
            nullable: true
            length: 2000
            options:
                fixed: false
            column: FP_PLUS
        fpConseils:
            type: string
            nullable: true
            length: 2000
            options:
                fixed: false
            column: FP_CONSEILS
        fpTempo:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: FP_TEMPO
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    oneToOne:
        fo:
            targetEntity: Fournisseurs
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                FO_ID:
                    referencedColumnName: FO_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
