ProductBundle\Entity\FournUsers:
    type: entity
    table: FOURN_USERS
    indexes:
        IDX_D914EAADE50C0AD7:
            columns:
                - FO_ID
    id:
        fcId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: FC_ID
            generator:
                strategy: IDENTITY
    fields:
        fcPrenom:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: FC_PRENOM
        fcNom:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: FC_NOM
        fcFonction:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: FC_FONCTION
        fcTel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: FC_TEL
        fcGsm:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: FC_GSM
        fcFax:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: FC_FAX
        fcMail:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: FC_MAIL
        fcPass:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: FC_PASS
        fcNiveau:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: FC_NIVEAU
        fcStatus:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: FC_STATUS
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    manyToOne:
        fo:
            targetEntity: Fournisseurs
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                FO_ID:
                    referencedColumnName: FO_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
