ProductBundle\Entity\ImportProduits:
    type: entity
    table: IMPORT_PRODUITS
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        partId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PART_ID
        fournisseur:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Fournisseur
        rayon:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Rayon
        famille:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Famille
        filtre1:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Filtre1
        valeur1:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Valeur1
        filtre2:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Filtre2
        valeur2:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Valeur2
        filtre3:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Filtre3
        valeur3:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Valeur3
        filtre4:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Filtre4
        valeur4:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Valeur4
        filtre5:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Filtre5
        valeur5:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Valeur5
        filtre6:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Filtre6
        valeur6:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Valeur6
        filtre7:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Filtre7
        valeur7:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Valeur7
        filtre8:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Filtre8
        valeur8:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Valeur8
        filtre9:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Filtre9
        valeur9:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Valeur9
        filtre10:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Filtre10
        valeur10:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Valeur10
        refPart:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Ref_Part
        refFourn:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Ref_Fourn
        ean:
            type: string
            nullable: true
            length: 13
            options:
                fixed: false
            column: EAN
        nomProduit:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: Nom_Produit
        descripCourte:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
            column: Descrip_Courte
        descripLongue:
            type: string
            nullable: true
            length: 5000
            options:
                fixed: false
            column: Descrip_Longue
        triptyque:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Triptyque
        qteCmde:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Qte_Cmde
        conditionnement:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Conditionnement
        prixPublicHt:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Prix_Public_HT
        prixPartHt:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Prix_Part_HT
        prixVc:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Prix_VC
        remisePct:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Remise_PCT
        typeLien:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Type_Lien
        lien:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: Lien
        photo:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: Photo
        variableSession:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Variable_Session
    lifecycleCallbacks: {  }
