ProductBundle\Entity\ProduitsPromo:
    type: entity
    table: PRODUITS_PROMO
    indexes:
        IDX_29E091BEA8DFE7B7:
            columns:
                - PR_ID
    id:
        ppId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PP_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        ppOrdre:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PP_ORDRE
        ppDate:
            type: datetime
            nullable: true
            column: PP_DATE
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
    manyToOne:
        pr:
            targetEntity: Produits
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PR_ID:
                    referencedColumnName: PR_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
