AchatCentrale\CrmBundle\Entity\ClientsGroupe:
    type: entity
    table: clients_groupe
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 140
            options:
                fixed: false
            column: Nom
    lifecycleCallbacks: {  }
