AchatCentrale\CrmBundle\Entity\ClientsNotes:
    type: entity
    table: CLIENTS_NOTES
    indexes:
        IDX_F77855983F592A49:
            columns:
                - CL_ID
    id:
        cnId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CN_ID
            generator:
                strategy: IDENTITY
    fields:
        cnNote:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: CN_NOTE
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    manyToOne:
        cl:
            targetEntity: Clients
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CL_ID:
                    referencedColumnName: CL_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
