AchatCentrale\CrmBundle\Entity\MessageFichiers:
    type: entity
    table: MESSAGE_FICHIERS
    indexes:
        IDX_6998CDC7FD61DBA2:
            columns:
                - ME_ID
    id:
        mfId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: MF_ID
            generator:
                strategy: IDENTITY
    fields:
        mdId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: MD_ID
        mfFichier:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: MF_FICHIER
        mfTaille:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: MF_TAILLE
        mfDate:
            type: datetime
            nullable: true
            column: MF_DATE
        mfTempo:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: MF_TEMPO
    manyToOne:
        me:
            targetEntity: MessageEntete
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ME_ID:
                    referencedColumnName: ME_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
