AchatCentrale\CrmBundle\Entity\PanierTemp:
    type: entity
    table: PANIER_TEMP
    id:
        ptId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PT_ID
            generator:
                strategy: IDENTITY
    fields:
        clId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CL_ID
        ccId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CC_ID
        foId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: FO_ID
        prId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PR_ID
        meId:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: ME_ID
        ptDate:
            type: date
            nullable: true
            column: PT_DATE
        ptQte:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: PT_QTE
        ptDetail:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: PT_DETAIL
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
    lifecycleCallbacks: {  }
