AchatCentrale\CrmBundle\Entity\Pays:
    type: entity
    table: PAYS
    id:
        paId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PA_ID
            generator:
                strategy: IDENTITY
    fields:
        paCode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: PA_CODE
        paDescr:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: PA_DESCR
        paProv:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: PA_PROV
    lifecycleCallbacks: {  }
