AchatCentrale\CrmBundle\Entity\Utilisateur:
    type: entity
    table: null
    repositoryClass: AchatCentrale\CrmBundle\Repository\UtilisateurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
