RocEclercBundle\Entity\Classif:
    type: entity
    table: CLASSIF
    id:
        clId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CL_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        clDescr:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CL_DESCR
    lifecycleCallbacks: {  }
