RocEclercBundle\Entity\Logs:
    type: entity
    table: LOGS
    id:
        loId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: LO_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        loIdent:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LO_IDENT
        loIdentNum:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: LO_IDENT_NUM
        loCode:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LO_CODE
        loDate:
            type: datetime
            nullable: true
            column: LO_DATE
        loDescr:
            type: string
            nullable: true
            length: 5000
            options:
                fixed: false
            column: LO_DESCR
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
    lifecycleCallbacks: {  }
