RocEclercBundle\Entity\Panier:
    type: entity
    table: PANIER
    indexes:
        IDX_D434CA743F592A49:
            columns:
                - CL_ID
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        meId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ME_ID
        idCommande:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ID_COMMANDE
        prId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PR_ID
        quantite:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: QUANTITE
        prixUht:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: PRIX_UHT
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    manyToOne:
        cl:
            targetEntity: Clients
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CL_ID:
                    referencedColumnName: CL_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
