RocEclercBundle\Entity\ProfilsFourn:
    type: entity
    table: PROFILS_FOURN
    indexes:
        IDX_84165EC03508DF0E:
            columns:
                - PU_ID
    id:
        pfId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: PF_ID
            generator:
                strategy: IDENTITY
    fields:
        foId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: FO_ID
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    manyToOne:
        pu:
            targetEntity: ProfilsUsers
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                PU_ID:
                    referencedColumnName: PU_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
