#View all
crm_home:
    defaults: { _controller: AchatCentraleCrmBundle:Site:Gestion }
    path:     /



#View all the client
vue_alll:
    defaults: { _controller: AchatCentraleCrmBundle:Site:ViewAllClient }
    path:     /client

#Add_new_client
new_client:
    defaults: { _controller: AchatCentraleCrmBundle:Site:NewClient }
    path:     /client/new

#Update_client
update_client:
    defaults: { _controller: AchatCentraleCrmBundle:Site:UpdateClient }
    path:     /client/update/{id}


#Delete_client
delete_client:
    defaults: { _controller: AchatCentraleCrmBundle:Site:DeleteClient}
    path:     /client/delete/{id}