login:
    path:     /login
    defaults: {_controller: SiteBundle:Security:login}

logout:
    path:      /logout


profile-update:
    path: /settings
    defaults: {_controller: SiteBundle:Base:updateProfil}


index_auth:
    path:     /
    defaults: { _controller: SiteBundle:Base:indexAuth}


client:
    path:     /client
    defaults: { _controller: SiteBundle:Base:Client }


client-new:
    path:     /client/new
    defaults: { _controller: SiteBundle:Base:ClientNew }

get-all-client:
    path:     /client/All
    defaults: {_controller: SiteBundle:Base:getAllClients}
    methods: GET

client-general:
    path:     /client/{id}/{centrale}/general
    defaults: { _controller: SiteBundle:Base:ClientGeneral }
    methods: GET


client-adresse:
    path:     /client/{id}/{centrale}/adresse
    defaults: { _controller: SiteBundle:Base:ClientAdresse }

client-status:
    path:     /client/{id}/{centrale}/status
    defaults: { _controller: SiteBundle:Base:ClientStatut }

client-facturation:
    path:     /client/{id}/{centrale}/facturation
    defaults: {_controller: SiteBundle:Base:ClientFacturation}

client-feed:
    path:    /client/{id}/{centrale}/feed
    defaults: {_controller: SiteBundle:Base:ClientFeed}


sendClientDetailMail:
    path:     /send/client/{clientId}
    defaults: {_controller: SiteBundle:Base:sendClientDetailMail}

get-raison-soc:
    path:     /client/raisonSoc/{id}/{centrale}
    defaults: {_controller: SiteBundle:Base:getClientRaisonSoc}

test:
    path:    /test
    defaults: {_controller: SiteBundle:Base:test}


test_param:
    path:    /test/{id}
    defaults: {_controller: SiteBundle:Base:testWithParam}


taches_home:
    path:    /taches
    defaults: {_controller: SiteBundle:Tache:Tache}

detail-task:
    path:   /taches/detail/{idCentrale}/{id}
    defaults: {_controller: SiteBundle:Tache:DetailTask}
new-task:
    path:   /taches/new
    defaults: {_controller: SiteBundle:Tache:NewTask}




archive-task:
    path: /taches/archive/{id}/{centrale}
    defaults: {_controller: SiteBundle:Tache:ArchiveTask}

delete-task:
    path:   /taches/delete/{id}/{centrale}
    defaults: {_controller: SiteBundle:Tache:DeleteTask}

update-task:
    path: /taches/update/{id}/{centrale}
    defaults: {_controller: SiteBundle:Tache:UpdateTask}


unarchive-task:
    path: /taches/unarchive/{id}
    defaults: {_controller: SiteBundle:Tache:UnArchiveTask}

mail-task:
    path: /taches/mail/{id}
    defaults: {_controller: SiteBundle:Tache:sendMailTask}

change-state:
    path: /taches/etat/{state}/{id}/{centrale}
    defaults: {_controller: SiteBundle:Tache:changetheState}

update-client-statut:
    path: /client/{id}/{centrale}/update/statut
    defaults: {_controller: SiteBundle:Base:updateStatut}
    methods: POST

update-client:
    path: /client/{id}/{centrale}/update
    defaults: {_controller: SiteBundle:Base:updateClient}
    methods: POST

new-clients-user:
    path: /client/{id}/{centrale}/users/new
    defaults: {_controller: SiteBundle:Base:newClientsUser}



add-notes:
    path: /client/{id}/{centrale}/notes/add
    defaults: {_controller: SiteBundle:Base:newNotesClient}
    methods: POST

get-user-autocomplete:
    path: /user/search/{query}
    defaults:  {_controller: SiteBundle:Base:getUserAutocomplete}

get-client-autocomplete:
    path: /client/search/{query}/{centrale}
    defaults: {_controller: SiteBundle:Base:getClientAutocomplete}


get-client-user:
    path: /client/user/{centrale}/{id}
    defaults: {_controller: SiteBundle:Base:getClientUser}