login:
    path:     /login
    defaults: {_controller: SiteBundle:Security:login}

logout:
    path:      /logout


index_auth:
    path:     /
    defaults: { _controller: SiteBundle:Base:indexAuth, reactRouting: null }
    requirements:
            reactRouting: ".+"

client:
    path:     /client
    defaults: { _controller: SiteBundle:Base:Client }

get-all-client:
    path:     /client/All
    defaults: {_controller: SiteBundle:Base:getAllClients}
    methods: GET

client-general:
    path:     /client/{id}/general
    defaults: { _controller: SiteBundle:Base:ClientGeneral }


client-adresse:
    path:     /client/{id}/adresse
    defaults: { _controller: SiteBundle:Base:ClientAdresse }

client-status:
    path:     /client/{id}/status
    defaults: { _controller: SiteBundle:Base:ClientStatut }

Who-Are-The-User:
    path:     /who/{type}
    defaults: { _controller: SiteBundle:Base:whoAre }

Count:
    path:     /Agence/count
    defaults: { _controller: SiteBundle:Base:countAgence }

sendClientDetailMail:
    path:     /send/client/{clientId}
    defaults: {_controller: SiteBundle:Base:sendClientDetailMail}

test:
    path:    /test
    defaults: {_controller: SiteBundle:Base:test}


test_param:
    path:    /test/{id}
    defaults: {_controller: SiteBundle:Base:testWithParam}


taches_home:
    path:    /taches
    defaults: {_controller: SiteBundle:Tache:Tache}

new-task:
    path:   /taches/new
    defaults: {_controller: SiteBundle:Tache:NewTask}
delete-task:
    path:   /taches/delete/{id}
    defaults: {_controller: SiteBundle:Tache:Delete}