login:
    path:   /login
    defaults: {_controller: SiteBundle:Security:login}
logout:
    path:   /logout

index_auth:
    path:     /
    defaults: { _controller: SiteBundle:Base:indexAuth }

client:
    path:     /client
    defaults: { _controller: SiteBundle:Base:client }


clientById:
    path:     /client/{id}
    defaults: { _controller: SiteBundle:Base:clientById }

settings:
    path:     /settings
    defaults: {_controller: SiteBundle:Base:settings}


test:
    path:    /test
    defaults: {_controller: SiteBundle:Base:test}


test_param:
    path:    /test/{id}
    defaults: {_controller: SiteBundle:Base:testWithParam}
