login:
    path:     /login
    defaults: {_controller: SiteBundle:Security:login}

logout:
    path:      /logout


profile-update:
    path: /settings
    defaults: {_controller: SiteBundle:Base:updateProfil}


index_auth:
    path:     /
    defaults: { _controller: SiteBundle:Base:indexAuth}


client:
    path:     /client
    defaults: { _controller: SiteBundle:Base:Client }


client-new:
    path:     /client/new
    defaults: { _controller: SiteBundle:Base:ClientNew }

get-all-client:
    path:     /client/All
    defaults: {_controller: SiteBundle:Base:getAllClients}
    methods: GET

client-general:
    path:     /client/{id}/{centrale}/general
    defaults: { _controller: SiteBundle:Base:ClientGeneral }
    methods: GET


client-adresse:
    path:     /client/{id}/{centrale}/adresse
    defaults: { _controller: SiteBundle:Base:ClientAdresse }

client-status:
    path:     /client/{id}/{centrale}/status
    defaults: { _controller: SiteBundle:Base:ClientStatut }

Who-Are-The-User:
    path:     /who/{type}
    defaults: { _controller: SiteBundle:Base:whoAre }

Count:
    path:     /Agence/count
    defaults: { _controller: SiteBundle:Base:countAgence }

sendClientDetailMail:
    path:     /send/client/{clientId}
    defaults: {_controller: SiteBundle:Base:sendClientDetailMail}

test:
    path:    /test
    defaults: {_controller: SiteBundle:Base:test}


test_param:
    path:    /test/{id}
    defaults: {_controller: SiteBundle:Base:testWithParam}


taches_home:
    path:    /taches
    defaults: {_controller: SiteBundle:Tache:Tache}

detail-task:
    path:   /taches/detail/{id}
    defaults: {_controller: SiteBundle:Tache:DetailTask}
new-task:
    path:   /taches/new
    defaults: {_controller: SiteBundle:Tache:NewTask}
delete-task:
    path:   /taches/delete/{id}
    defaults: {_controller: SiteBundle:Tache:Delete}
archive-task:
    path: /taches/archive/{id}
    defaults: {_controller: SiteBundle:Tache:ArchiveTask}

mail-task:
    path: /taches/mail/{id}
    defaults: {_controller: SiteBundle:Tache:sendMailTask}

update-task:
    path: /taches/update/{id}
    defaults: {_controller: SiteBundle:Base:updateProfil}

update-client:
    path: /client/{id}/{centrale}/update
    defaults: {_controller: SiteBundle:Base:updateClient}
    methods: POST

add-notes:
    path: /client/{id}/{centrale}/notes/add
    defaults: {_controller: SiteBundle:Base:newNotesClient}
    methods: POST