index:
    path:     /
    defaults: { _controller: SiteBundle:Base:index }
index_auth:
    path:     /home
    defaults: { _controller: SiteBundle:Base:indexAuth }

settings:
    path:     /settings
    defaults: {_controller: SiteBundle:Base:settings}

logout:
    path:     /logout
    defaults: {_controller: SiteBundle:Base:logout}


test:
    path:    /test
    defaults: {_controller: SiteBundle:Base:Client}