index_auth:
    path:     /
    defaults: { _controller: SiteBundle:Base:indexAuth, reactRouting: null }
    requirements:
            reactRouting: ".+"

client:
    path:     /client
    defaults: { client: null }
    requirements:
            client: ".+"

Who-Are-The-User:
    path:     /who/{type}
    defaults: { _controller: SiteBundle:Base:whoAre }

Count:
    path:     /Agence/count
    defaults: { _controller: SiteBundle:Base:countAgence }

sendClientDetailMail:
    path:     /send/client/{clientId}
    defaults: {_controller: SiteBundle:Base:sendClientDetailMail}

test:
    path:    /test
    defaults: {_controller: SiteBundle:Base:test}


test_param:
    path:    /test/{id}
    defaults: {_controller: SiteBundle:Base:testWithParam}
