services:
    site.twig.crm_filter:
        class: SiteBundle\Twig\CrmFilter
        arguments:
            doctrine: '@doctrine'
        tags:
            - { name: twig.extension}
    site.service.taches_utils:
        class: SiteBundle\Service\TachesUtils
    site.service.client_services:
        class: SiteBundle\Service\ClientServices
        arguments: [ '@doctrine.dbal.centrale_funecap_connection' ]
    site.service.feed_services:
        class: SiteBundle\Service\FeedServices
        arguments:
            doctrine: '@doctrine'
            tags:
                - { name: twig.extension}