services:
    site.twig.crm_filter:
        class: SiteBundle\Twig\CrmFilter
        arguments:
            doctrine: '@doctrine'
        tags:
            - { name: twig.extension}
    site.service.taches_utils:
        class: SiteBundle\Service\TachesUtils
    site.service.client_services:
        class: SiteBundle\Service\ClientServices
        arguments: [ '@doctrine.dbal.centrale_funecap_connection' ]
    site.service.bddservices:
        class: SiteBundle\Service\BddServices
        arguments: [ '@doctrine.dbal.achat_centrale_connection' ]
    site.service.centraleservices:
        class: SiteBundle\Service\CentraleServices
        arguments: [ '@doctrine.dbal.achat_centrale_connection' ]
    site.service.feed_services:
        class: SiteBundle\Service\FeedServices
        arguments:
            doctrine: '@doctrine'
            tags:
                - { name: twig.extension}
    site.service.mailer:
        class: SiteBundle\Service\Mailer
        arguments: ['@mailer', '@templating.engine.twig', '@doctrine.dbal.achat_centrale_connection']