services:
    site.twig.crm_filter:
        class: SiteBundle\Twig\CrmFilter
        tags:
            - { name: twig.extension}
    site.service.taches_utils:
        class: SiteBundle\Service\TachesUtils
