AchatCentraleBundle\Entity\CommandeDetail:
    type: entity
    table: COMMANDE_DETAIL
    indexes:
        IDX_8002F979425165C3:
            columns:
                - CE_ID
    id:
        cdId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CD_ID
            generator:
                strategy: IDENTITY
    fields:
        prId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PR_ID
        cdDate:
            type: datetime
            nullable: true
            column: CD_DATE
        cdQte:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CD_QTE
        cdDetail:
            type: string
            nullable: true
            length: 5
            options:
                fixed: false
            column: CD_DETAIL
        cdRef:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: CD_REF
        cdEan:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: CD_EAN
        cdNom:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: CD_NOM
        cdDescrCourte:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: CD_DESCR_COURTE
        cdPrixPublic:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CD_PRIX_PUBLIC
        cdPrixCa:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CD_PRIX_CA
        cdPrixVc:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: CD_PRIX_VC
        cdStatus:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CD_STATUS
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    manyToOne:
        ce:
            targetEntity: CommandeEntete
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CE_ID:
                    referencedColumnName: CE_ID
            orphanRemoval: false
    lifecycleCallbacks: {  }
