AchatCentraleBundle\Entity\Groupe:
    type: entity
    table: GROUPE
    id:
        grId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: GR_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        grDescr:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: GR_DESCR
    lifecycleCallbacks: {  }
