AchatCentraleBundle\Entity\MessageEntete:
    type: entity
    table: MESSAGE_ENTETE
    id:
        meId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ME_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        clId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CL_ID
        ccId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: CC_ID
        foId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: FO_ID
        fcId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: FC_ID
        prId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: PR_ID
        meDate:
            type: datetime
            nullable: true
            column: ME_DATE
        meSujet:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: ME_SUJET
        meNote:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
            column: ME_NOTE
        meStatus:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ME_STATUS
        meLuC:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ME_LU_C
        meLuF:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ME_LU_F
        meRelance:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ME_RELANCE
        meAdrFac:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ME_ADR_FAC
        meAdrLiv:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ME_ADR_LIV
        meCmde:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ME_CMDE
        meTempo:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: ME_TEMPO
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    lifecycleCallbacks: {  }
