AchatCentraleBundle\Entity\Tarifs:
    type: entity
    table: TARIFS
    id:
        taId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: TA_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        taEffectif:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: TA_EFFECTIF
        taUnite:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: TA_UNITE
        taPrix:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: TA_PRIX
        taPrixRemise:
            type: float
            nullable: true
            precision: 53
            scale: 0
            column: TA_PRIX_REMISE
        taDate:
            type: datetime
            nullable: true
            column: TA_DATE
    lifecycleCallbacks: {  }
