SiteBundle\Entity\Filtres:
    type: entity
    table: FILTRES
    id:
        fiId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: FI_ID
            generator:
                strategy: IDENTITY
    fields:
        soId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: SO_ID
        fiCode:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: FI_CODE
        fiValeur:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: FI_VALEUR
        insDate:
            type: datetime
            nullable: true
            column: INS_DATE
        insUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: INS_USER
        majDate:
            type: datetime
            nullable: true
            column: MAJ_DATE
        majUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: MAJ_USER
    lifecycleCallbacks: {  }
